language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
